name: Research Catalog Intake Template
description: Add your final research insights and artifacts to the research repository. 
title: "Project Name"
labels: ["Insights Library", "Research Library", "Product Research"]
projects: [unknown]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to add your research to the repository!
  - type: input
    id: project name
    attributes:
      label: Project Name
      description: Use a descriptive name that someone without context can understand
      placeholder: ex. Buyer trust in partnerships
    validations:
  - type: input
    id: project files
    attributes:
      label: Project File(s) 
      description: If your research is 1 file, add the single file. If your research is 2+ files, add the file folder. Make sure that your file is open to all of Shopify for viewing. 
      placeholder: file link or folder link 
    validations:
  - type: input
    id: videobin url
    attributes:
      label: Videobin URL
      description: If you have videos about your research, add them to [Videobin](https://videobin.shopify.io). If you have 1 video, add the link directly. If you have 2+ videos, create a Videobin playlist and add the link to the playlist.
      placeholder: videobin link 
    validations:
  - type: input
    id: dashboard prototype
    attributes:
      label: Dashboard or Prototype 
      description: If your research has a supporting prototype or dashboard, add the relevant link here. This includes Data Stories, Looker Studio, and Tableau. Make sure permission are viewable to all of Shopify.
      placeholder: dashboard or prototype link 
    validations:
  - type: input
    id: report date 
    attributes:
      label: Report Date (Year - Quarter) 
      description: Format should be as follows - Year - Q 
      placeholder: ie. 2023 Q1 
    validations:
  - type: textarea
    id: insights 
    attributes:
      label: Insights 
      description: You should create a [separate issue for each insight](https://github.com/Shopify/psn/issues/new?assignees=&labels=Insights+Library&projects=https%3A%2F%2Fgithub.com%2Forgs%2FShopify%2Fprojects%2F8809&template=capture_an_insight.yml&title=%5BProduct+or+Support+Stakeholder+team%5D+Descriptive+title+of+insight) that results from your study. We recommend identifying no more than (3) insights per research study. You should follow the format - Issue name - issue link. For more information on how to write issue name, see [PSN Insights Library Playbook](https://docs.google.com/document/d/17neVePhZKDHeTc-L-9AMVCzmCFak65MRMLsMA-2tSAg/edit)
      placeholder: Add your insights here 
  - type: textarea
    id: product impact 
    attributes:
      label: Product Impact
      description: How did the findings from this study impact your product area?
      placeholder: The findings from my study impacted …  
      value: 
    validations:
 - type: dropdown
    id: research type 
    attributes:
      label: Research Type
      Options:
	– Not selected
	- Vendor
	- UXer doing research
	- Support researcher
	- Product researcher
	- PM doing research
	- PCN (Product Commercial Network)
	- Market researcher
	- Data researcher
      default: 0
    validations:
  - type: checkboxes
    id: product area
    attributes:
      label: Product Area
      description: Product area(s) covered by this research 
      options:
	– Analytics and Data
	- Apps and Themes
	- Buyers
	- Competitive Landscape
	- Developer Experience
	- Finance
	- Inventory and Product Management 
	- Merchant experience 
	- Online Store 
	– Order Lifecycle
	- Partners
	- Recurring Research 
	- Segmentation
	- Shopify Marketing and Growth
	- Shopping and Sales Channel
type: checkboxes
    id: target group
    attributes:
      label: Target Group
      description: Product area(s) covered by this research 
      options:
	– Buyer 
	- Churned merchant
	- Competitor
	- Creator
	- Dropshipper
	- Established merchant
	- First-party developer
	- Influencer
	- Large merchant
	– Mature merchant
	- Merchant
	- Multi-channel merchant
	- Non-seller
	- Omni-channel merchant
	- Partner
	- Plus merchants
	- Pre-commerce / aspirational merchant 
	- Re-platformer
	- Seller
	- Shop App user
	- Shop Pay user 
	- Shopifolk
	- Single-channel merchant
	– Small to medium sized business (SMB)
	- Staff
	- Third-party developer
type: checkboxes
    id: region
    attributes:
      label: Region
      options:
	  – Americas 
          - Asia-Pacific (APAC)
          - Asia
          - Australia
          - Austria
          - Belgium
          - Brazil
          - Canada
          - Chile
          – China
          - Colombia
          - Costa Rica
          - Denmark
          - Europe, the Middle East and Africa (EMEA)
          - Europe
          - Finland
          - France
          - Germany
          - Worldwide / Global
          - Guatemala]
          - Hong Kong 
          - India
          - Iran
          – Ireland
          - Italy
          - Japan
          - Lithuania
          - Mexico
          - Netherlands
          - New Zealand
          – Nigeria
          - Panama
          - Philippines
          - Portugal
          - Puerto Rico
          - Singapore
          - South Africa
          - Spain
          - Sweden
          - Syria
          – Taiwan
          - Turkey
          - United Kingdom (UK)
          - United States (US)
          - US East 
          - US West
	  required: true 
type: checkboxes
    id: research method
    attributes:
      label: Research Method
      options:
	– A/B test 
	- Accessibility audit
	- App analysis
	- Capability analysis 
	- Card sort 
	- Comparative analysis
	- Competitive research
	- Concept test
	- Data analysis
	– Diary study
	- Focus group
	- Foresight research
	- Interview 
	- Merchant empathy / exposure 
	- Mixed methods
	- Moderated test
	- Primary research 
	- Qualitative research 
	- Quantitative research
	- Secondary research
	- Statistical analysis
	- Support ticket dive
	- Survey
	– Tree test
	- Unmoderated test
	- Usability test
 - type: textarea
    id: keywords
    attributes:
      label: Keywords
      description: Separate any relevant keywords by commas. This can include product-related keywords, team names, or stage of business not reflected elsewhere.
      render: shell
